# Generated by Django 4.0.2 on 2022-03-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.Question'),
        ),
    ]
